jog_joint_node:
  joint_names:
    - left_s0
    - left_s1
    - left_e0
    - left_e1
    - left_w0
    - left_w1
    - left_w2
    - right_s0
    - right_s1
    - right_e0
    - right_e1
    - right_w0
    - right_w1
    - right_w2

jog_frame_node:
  group_names:
    - left_arm
    - right_arm
  link_names:
    - left_hand
    - right_hand
  exclude_joint_names:
    - head_nod