joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

/robot/limb/right:
    type: position_controllers/JointTrajectoryController
    joints:
      - right_s0
      - right_s1
      - right_e0
      - right_e1
      - right_w0
      - right_w1
      - right_w2

/robot/limb/left:
    type: position_controllers/JointTrajectoryController
    joints:
      - left_s0
      - left_s1
      - left_e0
      - left_e1
      - left_w0
      - left_w1
      - left_w2
