jog_joint_node:
  joint_names:
    - crane_x7_shoulder_fixed_part_pan_joint
    - crane_x7_shoulder_revolute_part_tilt_joint
    - crane_x7_upper_arm_revolute_part_twist_joint
    - crane_x7_upper_arm_revolute_part_rotate_joint
    - crane_x7_lower_arm_fixed_part_joint
    - crane_x7_lower_arm_revolute_part_joint
    - crane_x7_wrist_joint

jog_frame_node:
  group_names:
    - arm
  link_names:
    - crane_x7_gripper_base_link

move_group:
  controller_list:
    - name: /crane_x7/arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
        - crane_x7_shoulder_fixed_part_pan_joint
        - crane_x7_shoulder_revolute_part_tilt_joint
        - crane_x7_upper_arm_revolute_part_twist_joint
        - crane_x7_upper_arm_revolute_part_rotate_joint
        - crane_x7_lower_arm_fixed_part_joint
        - crane_x7_lower_arm_revolute_part_joint
        - crane_x7_wrist_joint
