jog_joint_node:
  joint_names:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

jog_frame_node:
  group_names:
    - manipulator
  link_names:
    - ee_link

# Somehow, UR5 moveit doesn't have controller name, so specify here
move_group:
  controller_list:
    - name: arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint
